/* Generated By:JavaCC: Do not edit this line. AnalisadorTreeConstants.java Version 5.0 */
public interface AnalisadorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTGOAL = 1;
  public int JJTMAINCLASS = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTTYPE = 6;
  public int JJTSTATEMENT = 7;
  public int JJTELINHA = 8;
  public int JJTEXPRESSION = 9;


  public String[] jjtNodeName = {
    "Start",
    "Goal",
    "MainClass",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "Type",
    "Statement",
    "Elinha",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=44b2a240065e6ed737b31ff80b4a5960 (do not edit this line) */
